### ISSUE TITLE
summary timing out

### ISSUE THREAD

**Issue by cscherrer** [hakaru-dev/hakaru#46] opened 2017-03-29 19:29 UTC
For [this code](https://gist.github.com/cscherrer/f6b6b6a5f5b191b8d31e78ef12d6d9e2) `summary` is timing out, but `compile` returns a result almost immediately.

**Comment by JacquesCarette** [comment] 2017-04-20 15:00
`summary` is mostly Maple code written by Ken, so I'm assigning him to look at it.  Strange that @zaxtax did not already do this...

**Comment by zaxtax** [comment] 2017-04-20 15:58
Well I haven't had issues with it timing out. But this is good to know
about.

**Comment by ccshan** [comment] 2017-04-20 18:46
The particular input expression that Chad gisted when he opened this issue was produced by a run of `simplify` that suffered from multiple bugs: `betaFunc` was not hacked away, and the indentation-sensitive concrete Hakaru syntax was not pretty-printed correctly so as to roundtrip. Now that `simplify` no longer suffers from those bugs, it's not so urgent to make `summary` behave on this particular input expression. But feeding this input expression to `summary` still times out today on the `master` branch. I narrowed it down to this call to `KB:-assert` (via `simplify_factor_assuming`):

```
restart: with(Hakaru): with(Summary):
trace(KB:-assert_deny);
trace(KB:-assert_deny:-bound_simp);
KB:-assert(And(Not(zNewä¸+1 = size(topic_prior)), iä¸ = zNewä¸), KB:-build_unsafely([Introduce(iä¸, HInt(Bound(`>=`, 0), Bound(`<=`, size(topic_prior)-2))), Introduce(j, HInt(Bound(`>=`, 0), Bound(`<=`, Let(Bucket(Fanout(Split(docUpdate = idx(doc, iä¸), Index(size(word_prior), iä¸£, idx(w, iä¸), Add(1)), Nop()), Nop()), iä¸ = 0 .. size(w)-1), summary, piecewise(i = zNewä¸, idx(fst(fst(summary)), iä¸£), 0))-1))), Introduce(iä¸£, HInt(Bound(`>=`, 0), Bound(`<=`, size(word_prior)-1))), Introduce(i, HInt(Bound(`>=`, 0), Bound(`<=`, size(topic_prior)-1))), Introduce(zNewä¸, HInt(Bound(`>=`, 0), Bound(`<=`, size(topic_prior)-1))), Introduce(docUpdate, HInt(Bound(`>=`, 0))), Introduce(doc, HArray(HInt(Bound(`>=`, 0)))), Introduce(w, HArray(HInt(Bound(`>=`, 0)))), Introduce(z, HArray(HInt(Bound(`>=`, 0)))), Introduce(word_prior, HArray(HReal(Bound(`>=`, 0)))), Introduce(topic_prior, HArray(HReal(Bound(`>=`, 0))))]));
```

**Comment by ccshan** [comment] 2017-04-20 18:50
Oops, the Unicode was mangled in the command above. It should have been:
```
restart: with(Hakaru): with(Summary):
trace(KB:-assert_deny);
trace(KB:-assert_deny:-bound_simp);
KB:-assert(And(Not(zNew丏+1 = size(topic_prior)), i不 = zNew丏), KB:-build_unsafely([Introduce(i不, HInt(Bound(`>=`, 0), Bound(`<=`, size(topic_prior)-2))), Introduce(j, HInt(Bound(`>=`, 0), Bound(`<=`, Let(Bucket(Fanout(Split(docUpdate = idx(doc, i丙), Index(size(word_prior), i丣, idx(w, i丙), Add(1)), Nop()), Nop()), i丙 = 0 .. size(w)-1), summary, piecewise(i = zNew丏, idx(fst(fst(summary)), i丣), 0))-1))), Introduce(i丣, HInt(Bound(`>=`, 0), Bound(`<=`, size(word_prior)-1))), Introduce(i, HInt(Bound(`>=`, 0), Bound(`<=`, size(topic_prior)-1))), Introduce(zNew丏, HInt(Bound(`>=`, 0), Bound(`<=`, size(topic_prior)-1))), Introduce(docUpdate, HInt(Bound(`>=`, 0))), Introduce(doc, HArray(HInt(Bound(`>=`, 0)))), Introduce(w, HArray(HInt(Bound(`>=`, 0)))), Introduce(z, HArray(HInt(Bound(`>=`, 0)))), Introduce(word_prior, HArray(HReal(Bound(`>=`, 0)))), Introduce(topic_prior, HArray(HReal(Bound(`>=`, 0))))]));
```

**Comment by ccshan** [comment] 2017-04-20 18:51
@JacquesCarette, @yuriy0, running the above makes my Maple do this:
```
                c := Bound(<=, Hakaru:-size[topic_prior] - 1)

memory used=521.7MB, alloc=76.3MB, time=7.76
memory used=591.9MB, alloc=76.3MB, time=8.84
memory used=661.6MB, alloc=76.3MB, time=10.00
memory used=731.4MB, alloc=76.3MB, time=11.08
memory used=801.4MB, alloc=76.3MB, time=12.16
memory used=871.5MB, alloc=108.3MB, time=13.20
memory used=978.2MB, alloc=108.3MB, time=14.75
memory used=1084.5MB, alloc=108.3MB, time=16.31
memory used=1190.7MB, alloc=108.3MB, time=17.98
memory used=1297.3MB, alloc=108.3MB, time=19.68
memory used=1403.5MB, alloc=108.3MB, time=21.36
memory used=1509.3MB, alloc=140.3MB, time=23.07
memory used=1652.4MB, alloc=148.6MB, time=25.31
memory used=1794.2MB, alloc=148.7MB, time=27.61
memory used=1935.6MB, alloc=148.8MB, time=29.82
memory used=2077.6MB, alloc=181.4MB, time=32.03
memory used=2256.1MB, alloc=181.4MB, time=34.69
memory used=2433.6MB, alloc=181.6MB, time=37.39
memory used=2611.1MB, alloc=181.9MB, time=40.08
memory used=2788.9MB, alloc=182.5MB, time=42.85
```
Please look into it?

**Comment by JacquesCarette** [comment] 2017-04-20 19:06
Yuriy is likely offline for a month.  I will try to take a look.  But since it seems to be lower priority now as it is not blocking, it will indeed be 'lower priority'.

**Comment by JacquesCarette** [comment] 2017-08-15 15:06
Bump.  @yuriy0 can you check if this is still an issue?  If it is, then we can figure out how to prioritize it.

**Comment by yuriy0** [comment] 2017-08-15 16:05
Calling `Summarize` on the original program in question now produces an error:
```
Error, (in PiecewiseTools:-Is) Wrong kind of parameters in piecewise
```
(I haven't investigated this further).

The minimal example producing an infinite loop given by Ken no longer produces an infinite loop. However, it does take a very long time. The culprit is https://github.com/hakaru-dev/hakaru/blob/14990fccf487d8a02a5bf4cd0fc8bdefba05e75c/maple/KB.mpl#L364-L367

(in particular, the combination of `is` and `assuming`)

**Comment by JacquesCarette** [comment] 2017-08-15 16:16
That `piecewise` error is usually encountered when you do `piecewise(foo, ...)` when `foo` is a boolean variable.  It insists on `foo = true` instead.  But that's just a guess.

`is` can be extremely time consuming.  Sometimes that is legitimate, sometimes it is because it is asked a silly question and yet `is` still tries very hard to answer it.

**Comment by yuriy0** [comment] 2017-08-15 16:37
> is can be extremely time consuming. Sometimes that is legitimate, sometimes it is because it is asked a silly question and yet is still tries very hard to answer it.

I think that in this case it is the latter. The context passed to `assuming` is huge, and most of it is entirely irrelevant to the question.
```
> ctx0 := {(y <= Hakaru:-size[topic_prior]-1, y::integer, i不 = zNew丏, j::integer, 0 <= j, j <= Let(Bucket(Fanout(Split(docUpdate = Hakaru:-idx[doc, i丙], Index(Hakaru:-size[word_prior], i丣, Hakaru:-idx[w, i丙], Add(1)), Nop()), Nop()), i丙 = 0 .. Hakaru:-size[w]-1), summary, PIECEWISE([Hakaru:-idx[Hakaru:-fst(Hakaru:-fst(summary)), i丣], i = zNew丏], [0, otherwise]))-1, i丣::integer, 0 <= i丣, i丣 <= Hakaru:-size[word_prior]-1, i::integer, 0 <= i, i <= Hakaru:-size[topic_prior]-1, zNew丏::integer, 0 <= zNew丏, zNew丏 <= Hakaru:-size[topic_prior]-1, docUpdate::integer, 0 <= docUpdate, doc::TopProp, w::TopProp, z::TopProp, word_prior::TopProp, topic_prior::TopProp, (Hakaru:-size[w])::nonnegint, (Hakaru:-size[topic_prior])::nonnegint, (Hakaru:-size[word_prior])::nonnegint, (Hakaru:-idx[doc, i丙])::integer, (Hakaru:-idx[w, i丙])::integer, 0 <= Hakaru:-idx[doc, i丙], 0 <= Hakaru:-idx[w, i丙])}:
> cond0 := y <= Hakaru:-size[topic_prior]-2:
```
The call to `is(cond0) assuming op(ctx0)` takes several minutes, but `is(cond0) assuming op(select(depends, ctx0, indets(cond0, name)))` returns instantly. They both produce the same thing (which is `FAIL`). The entire context contains 29 operands, and the `select`ed one contains five (!). I'm not sure if this optimization would be valid in general, but it may be worth trying.

**Comment by JacquesCarette** [comment] 2017-08-15 20:52
It would be good to know if `assuming`, on its own, takes a lot of time.  That might be a plain bug.

In theory, `is` looks things up in its database on an as-needed basis.  Of course, it might need to chain knowledge to get there.  So if we ask `is(a<f)` after doing `assuming (a<b, b<c, c<d, c<e, d<e, e<f)`, for example, we can't just take everything out that does not mention`a` or `f`.

However, in this example"
1. I see no point in inserting a `Let(Bucket(...))` in the database. Especially with that containing all sorts of things that refer to variables that are linked to variables that mention y and/or topic_prior
2. Having `doc::TopProp`, (and same for w, z, word_prior, topic_prior) may well make things worse.  Why are they there?

My guess is that it is the Bucket expression which is the real source of the problem, the rest, even if large, is not.

**Comment by yuriy0** [comment] 2017-08-15 22:46
> It would be good to know if assuming, on its own, takes a lot of time.

It doesn't; the call to `is` is entered almost immediately (and it is what takes a long time).

> So if we ask is(a<f) after doing assuming (a<b, b<c, c<d, c<e, d<e, e<f), for example, we can't just take everything out that does not mentiona or f.

Indeed, which is why "I'm not sure if this optimization would be valid in general" - if such cases arise, or if the semantics of KB or solving would somehow get rid of them.

> I see no point in inserting a Let(Bucket(...)) in the database.
> My guess is that it is the Bucket expression which is the real source of the problem

Indeed, this seems to be the case (that `Bucket` is what is causing this to be so slow). I'm not sure exactly where it came from; it appears in the original minimal example given by Ken. There is an entry in the KB of the form
```
Introduce(j, HInt(Bound(`>=`, 0), Bound(`<=`, Let(Bucket( ... )))))
```

> Having doc::TopProp, (and same for w, z, word_prior, topic_prior) may well make things worse.

It doesn't seem to affect the runtime significantly. They are produced by https://github.com/hakaru-dev/hakaru/blob/14990fccf487d8a02a5bf4cd0fc8bdefba05e75c/maple/KB.mpl#L881-L885.

**Comment by JacquesCarette** [comment] 2017-08-15 23:17
There are properties called vector, matrix, SquareMatrix, etc.  See ?property.  That should cover some additional cases (like the 4 in this case).

Otherwise, I do think that remove all thinks that use `Let` (never mind `Bucket`) will probably be the best approximation.

**Comment by ccshan** [comment] 2017-08-15 23:44
The `Let(Bucket(...),...)` that I posted here on April 20 is generated by `SummarizeKB`, but 32 minutes later I seem to have committed a change (321883c15ccb55b6eec4dc433968194117acff72) that makes `SummarizeKB` put `sum(...)` instead of `Let(Bucket(...),...)` in the KB. So what's currently needed is probably not removing anything involving `Let` or `Bucket` but (if anything) something involving `sum`. But to figure out what that something is, we should run `Summarize` on Chad's original program, which as Yuriy noted produces `Error, (in PiecewiseTools:-Is) Wrong kind of parameters in piecewise`.

**Comment by yuriy0** [comment] 2017-08-15 23:51
> we should run Summarize on Chad's original program

I'll begin with fixing that error and then see if this call to `assert` is still an issue.

**Comment by yuriy0** [comment] 2017-08-16 20:18
The call to `assert` is indeed still an issue. The issue is worse with `Sum` than with `Bucket` in the sense that the call to `is` takes even longer (so long I've yet to see it complete - about 15 mins. minimum).

The offending call is
```
> arg1 := y <= Hakaru:-size[topic_prior]-2;
> ctx1 := y <= Hakaru:-size[topic_prior]-1, y::integer, iT = zNew0, j::integer, 0 <= j, j <= Sum(piecewise(docUpdate = Hakaru:-idx[doc, i2], piecewise(And(i = zNew0, i1 = Hakaru:-idx[w, i2]), 1, 0), 0), i2 = 0 .. Hakaru:-size[w]-1)-1, i1::integer, 0 <= i1, i1 <= Hakaru:-size[word_prior]-1, i::integer, 0 <= i, i <= Hakaru:-size[topic_prior]-1, zNew0::integer, 0 <= zNew0, zNew0 <= Hakaru:-size[topic_prior]-1, docUpdate::integer, 0 <= docUpdate, docUpdate <= Hakaru:-size[z]-1, doc::TopProp, w::TopProp, z::TopProp, word_prior::TopProp, topic_prior::TopProp, (Hakaru:-size[w])::nonnegint, (Hakaru:-size[z])::nonnegint, (Hakaru:-size[topic_prior])::nonnegint, (Hakaru:-size[word_prior])::nonnegint, (Hakaru:-idx[doc, i2])::integer, (Hakaru:-idx[w, i2])::integer, 0 <= Hakaru:-idx[doc, i2], 0 <= Hakaru:-idx[w, i2];
> is(arg1) assuming ctx1
```
And, like in the `Bucket` case, the `Sum` is the issue. The following
```
is(arg1) assuming op(remove(has,[ctx1],Sum))
```
returns instantly.

> There are properties called vector, matrix, SquareMatrix, etc. See ?property. That should cover some additional cases (like the 4 in this case).

But those cannot have parameters, so what is the model for `HArray(HInt)`? Just `vector`? And what is the model for e.g. `HArray(HArrya(HInt))`? Should it continue to be `TopProp`?

> Otherwise, I do think that remove all thinks that use Let (never mind Bucket) will probably be the best approximation.

Does this apply to `Sum` (and `Product`, `Int`) as well?

**Comment by JacquesCarette** [comment] 2017-08-17 00:04
Yes, it also applies to those.

My temptation would be to replace such expressions in assumptions with fresh symbols (that have as indicies the variables they depend on - a la 'chill'), and then add the assumption that that fresh symbol is real (as that's is likely true!).

**Comment by yuriy0** [comment] 2017-09-05 18:49
08b1608888a512b1c9fce12f6eab5fe45c5d926c and 40be4c62900a6ce8a0fa6045f190fc487db04cf8 increase the types of assumptions which will be ignored (i.e. 'bad' assumptions). This avoids the very expensive `is(..) assuming(..)` call (and similarly expensive `simplify(..) assuming (..)` call later on).

We could try to weaken the problematic constraint by 'estimation' to try to retain some information (in this case, replace `j <= Sum(f(i),i=0..size(as)-1)-1` with `j <= (size(as)-1)-1` where `f(i) in {0,1}` for all `i`) , but this is likely not necessary. I think the program in question is somewhat outdated as well.

**Closed by yuriy0** 2017-09-05 18:49 UTC
